"""Document verification: the mark a printed report carries, and what it proves.

A finalized report is checked against the record it came from without an
account. The QR code in the document opens the verification page for that
report's code; the page reads ``GET /api/v1/verify/{code}``, which recomputes
the content hash of the stored snapshot and compares it with the hash recorded
when the report was generated.

The QR encoder is ReportLab's, which is already a rendering dependency, and the
bitmap is written here with the standard library so no image library is needed
to embed the mark in the DOCX.
"""

from __future__ import annotations

import io
import struct
import zlib

from app.config import settings

#: The public page that answers a verification code.
VERIFICATION_PATH = "/verification.html"

#: Quiet zone mandated by ISO/IEC 18004, in modules, on every side.
QUIET_ZONE_MODULES = 4


class VerificationUnavailable(RuntimeError):
    """The QR encoder could not be reached."""


def verification_url(code: str | None) -> str | None:
    """The public address that verifies ``code``, or None when it is unknown.

    ``PUBLIC_APP_URL`` names the deployed frontend. A report generated by an
    instance that has not been told its own public address carries no QR code,
    rather than a code that leads nowhere.
    """
    base = settings.public_app_url
    if not base or not code:
        return None
    return f"{base}{VERIFICATION_PATH}?code={code.strip().upper()}"


def qr_matrix(payload: str, *, error_level: str = "M") -> list[list[bool]]:
    """The QR module matrix for ``payload``: True is a dark module."""
    from reportlab.graphics.barcode.qr import QrCodeWidget

    widget = QrCodeWidget(payload, barLevel=error_level)
    code = widget.qr
    code.make()
    count = code.moduleCount
    return [[bool(code.isDark(row, col)) for col in range(count)] for row in range(count)]


def _png_chunk(kind: bytes, payload: bytes) -> bytes:
    return (
        struct.pack(">I", len(payload))
        + kind
        + payload
        + struct.pack(">I", zlib.crc32(kind + payload) & 0xFFFFFFFF)
    )


def png_bytes(rows: list[list[bool]], *, scale: int = 6, quiet: int = QUIET_ZONE_MODULES) -> bytes:
    """Encode a module matrix as a greyscale PNG, one pixel per module * scale.

    Written here rather than delegated to an image library: the encoder is 20
    lines of the standard library, and a report must not fail to render because
    an optional drawing backend is missing from the image.
    """
    modules = len(rows)
    if modules == 0 or scale < 1:
        raise ValueError("a QR matrix must have at least one module and a positive scale")
    side = (modules + 2 * quiet) * scale
    raw = bytearray()
    for pixel_y in range(side):
        raw.append(0)  # PNG filter: none
        module_y = pixel_y // scale - quiet
        line = bytearray()
        for pixel_x in range(side):
            module_x = pixel_x // scale - quiet
            dark = (
                0 <= module_y < modules
                and 0 <= module_x < modules
                and rows[module_y][module_x]
            )
            value = 0 if dark else 255
            line += bytes((value, value, value))
        raw += line
    header = struct.pack(">IIBBBBB", side, side, 8, 2, 0, 0, 0)  # 8-bit truecolour
    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", header)
        + _png_chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + _png_chunk(b"IEND", b"")
    )


def qr_png(payload: str, *, scale: int = 6) -> bytes:
    return png_bytes(qr_matrix(payload), scale=scale)


def qr_drawing(payload: str, *, size: float):
    """A ReportLab drawing of the QR code, placed directly in the PDF story."""
    from reportlab.graphics.barcode.qr import QrCodeWidget
    from reportlab.graphics.shapes import Drawing

    widget = QrCodeWidget(payload, barLevel="M")
    x1, y1, x2, y2 = widget.getBounds()
    width = max(x2 - x1, 1)
    height = max(y2 - y1, 1)
    drawing = Drawing(size, size, transform=[size / width, 0, 0, size / height, 0, 0])
    drawing.add(widget)
    return drawing