"""initial schema

Revision ID: 0001
Revises: 
Created: 2026-09-29 19:33:11.772874

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
# Plain `Text` is imported because Alembic renders JSONB's astext_type without
# the `sa.` prefix, which would otherwise be a NameError at migration time.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_events',
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('test_instance_id', sa.Uuid(), nullable=True),
    sa.Column('attachment_id', sa.Uuid(), nullable=True),
    sa.Column('feature_code', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('input_reference', sa.String(length=512), nullable=True),
    sa.Column('output_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('user_disposition', sa.String(length=24), nullable=True),
    sa.Column('disposition_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_events_feature_code'), ['feature_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_events_test_instance_id'), ['test_instance_id'], unique=False)

    op.create_table('applicants',
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('organisation_type', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applicants_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_applicants_name'), ['name'], unique=False)

    op.create_table('audit_logs',
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=64), nullable=True),
    sa.Column('laboratory_id', sa.Uuid(), nullable=True),
    sa.Column('field_changed', sa.String(length=120), nullable=True),
    sa.Column('before_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('after_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_laboratory_id'), ['laboratory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('laboratories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('accreditation_no', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laboratories_code'), ['code'], unique=True)

    op.create_table('manufacturers',
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manufacturers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_manufacturers_name'), ['name'], unique=False)

    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('rules',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('clause_reference', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_code'), ['code'], unique=True)

    op.create_table('standards',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standards_code'), ['code'], unique=True)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('instruments',
    sa.Column('manufacturer_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('type_designation', sa.String(length=160), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('instrument_class', sa.String(length=8), nullable=False),
    sa.Column('max_capacity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('min_capacity', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('e', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('d', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('is_electronic', sa.Boolean(), nullable=False),
    sa.Column('is_multi_range', sa.Boolean(), nullable=False),
    sa.Column('is_multi_interval', sa.Boolean(), nullable=False),
    sa.Column('has_tare_device', sa.Boolean(), nullable=False),
    sa.Column('has_zero_device', sa.Boolean(), nullable=False),
    sa.Column('has_level_indicator', sa.Boolean(), nullable=False),
    sa.Column('temperature_range', sa.String(length=80), nullable=True),
    sa.Column('power_supply', sa.String(length=120), nullable=True),
    sa.Column('configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_instrument_class'), ['instrument_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_manufacturer_id'), ['manufacturer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_serial_number'), ['serial_number'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('permission_code', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['permissions.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code', 'permission_code', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_code'), ['permission_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_code'), ['role_code'], unique=False)

    op.create_table('standard_versions',
    sa.Column('standard_id', sa.Uuid(), nullable=False),
    sa.Column('edition', sa.String(length=40), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_id', 'version_label', name='uq_standard_version')
    )
    with op.batch_alter_table('standard_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_versions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_standard_versions_standard_id'), ['standard_id'], unique=False)

    op.create_table('test_equipment',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('equipment_type', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('serial_no', sa.String(length=120), nullable=True),
    sa.Column('nominal_value', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('accuracy_class', sa.String(length=40), nullable=True),
    sa.Column('laboratory_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_equipment_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_test_equipment_laboratory_id'), ['laboratory_id'], unique=False)

    op.create_table('users',
    sa.Column('supabase_user_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('laboratory_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_laboratory_id'), ['laboratory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_code'), ['role_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_supabase_user_id'), ['supabase_user_id'], unique=True)

    op.create_table('equipment_calibrations',
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_no', sa.String(length=120), nullable=True),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('uncertainty', sa.String(length=80), nullable=True),
    sa.Column('certificate_attachment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['test_equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_calibrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_calibrations_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_calibrations_valid_until'), ['valid_until'], unique=False)

    op.create_table('instrument_ranges',
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('range_no', sa.Integer(), nullable=False),
    sa.Column('min_capacity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('max_capacity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('e', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('d', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument_ranges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrument_ranges_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('link_url', sa.String(length=512), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('report_templates',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('standard_version_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_code'), ['code'], unique=True)

    op.create_table('rule_versions',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('standard_version_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('threshold', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('applicability', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('rounding_policy', sa.String(length=200), nullable=True),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('reviewed_by', sa.String(length=160), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version_label', name='uq_rule_version')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_versions_standard_version_id'), ['standard_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_versions_version_label'), ['version_label'], unique=False)

    op.create_table('test_definitions',
    sa.Column('test_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('standard_version_id', sa.Uuid(), nullable=False),
    sa.Column('clause_reference', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applicability_expression', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('input_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('validation_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('calculation_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('compliance_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('report_section_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_definitions_standard_version_id'), ['standard_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_definitions_test_code'), ['test_code'], unique=False)

    op.create_table('report_template_versions',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('section_map', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version_label', name='uq_template_version')
    )
    with op.batch_alter_table('report_template_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_template_versions_template_id'), ['template_id'], unique=False)

    op.create_table('evaluation_cases',
    sa.Column('application_no', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=True),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=True),
    sa.Column('laboratory_id', sa.Uuid(), nullable=False),
    sa.Column('engineer_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('standard_version_id', sa.Uuid(), nullable=True),
    sa.Column('template_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('scope_notes', sa.Text(), nullable=True),
    sa.Column('test_plan_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('test_plan_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_correction_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_version_id'], ['report_template_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_cases_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_application_no'), ['application_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_engineer_id'), ['engineer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_laboratory_id'), ['laboratory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_manufacturer_id'), ['manufacturer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_standard_version_id'), ['standard_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_status'), ['status'], unique=False)

    op.create_table('attachments',
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('storage_backend', sa.String(length=24), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('extension', sa.String(length=16), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('category_source', sa.String(length=16), nullable=False),
    sa.Column('classification_confidence', sa.String(length=16), nullable=True),
    sa.Column('is_malware_scanned', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_sha256'), ['sha256'], unique=False)

    op.create_table('case_assignments',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'user_id', 'role_code', name='uq_case_assignment')
    )
    with op.batch_alter_table('case_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_assignments_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('generated_reports',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('report_no', sa.String(length=60), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('case_revision_no', sa.Integer(), nullable=False),
    sa.Column('standard_version_id', sa.Uuid(), nullable=True),
    sa.Column('template_version_id', sa.Uuid(), nullable=True),
    sa.Column('ruleset_label', sa.String(length=80), nullable=True),
    sa.Column('template_label', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('data_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('verification_code', sa.String(length=32), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_version_id'], ['report_template_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_reports_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_report_no'), ['report_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_generated_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_verification_code'), ['verification_code'], unique=True)

    op.create_table('test_instances',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('test_definition_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('applicability_status', sa.String(length=24), nullable=False),
    sa.Column('applicability_reason', sa.Text(), nullable=True),
    sa.Column('applicability_trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('result_status', sa.String(length=24), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('is_waived', sa.Boolean(), nullable=False),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_definition_id'], ['test_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_instances_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_instances_result_status'), ['result_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_instances_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_instances_test_definition_id'), ['test_definition_id'], unique=False)

    op.create_table('workflow_actions',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('target_test_instance_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_actions_acted_at'), ['acted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_actions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_actions_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_actions_case_id'), ['case_id'], unique=False)

    op.create_table('attachment_links',
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('test_instance_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('linked_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_instance_id'], ['test_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachment_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_links_attachment_id'), ['attachment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_links_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_links_test_instance_id'), ['test_instance_id'], unique=False)

    op.create_table('calculation_runs',
    sa.Column('test_instance_id', sa.Uuid(), nullable=False),
    sa.Column('test_code', sa.String(length=64), nullable=False),
    sa.Column('rule_version_label', sa.String(length=80), nullable=True),
    sa.Column('standard_version_id', sa.Uuid(), nullable=True),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('intermediates', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('outputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('units', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('rounding_policy', sa.String(length=80), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_instance_id'], ['test_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculation_runs_test_code'), ['test_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculation_runs_test_instance_id'), ['test_instance_id'], unique=False)

    op.create_table('environmental_conditions',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('test_instance_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('relative_humidity_pct', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('barometric_pressure_kpa', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('air_density_kg_m3', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_instance_id'], ['test_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environmental_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environmental_conditions_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environmental_conditions_test_instance_id'), ['test_instance_id'], unique=False)

    op.create_table('manual_overrides',
    sa.Column('test_instance_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.String(length=24), nullable=False),
    sa.Column('new_status', sa.String(length=24), nullable=False),
    sa.Column('previous_value', sa.String(length=120), nullable=True),
    sa.Column('new_value', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_instance_id'], ['test_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_overrides_test_instance_id'), ['test_instance_id'], unique=False)

    op.create_table('report_revisions',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=12), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('case_revision_no', sa.Integer(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['generated_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_revisions_report_id'), ['report_id'], unique=False)

    op.create_table('test_equipment_usage',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('test_instance_id', sa.Uuid(), nullable=True),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['test_equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_instance_id'], ['test_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_equipment_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_equipment_usage_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_equipment_usage_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_equipment_usage_test_instance_id'), ['test_instance_id'], unique=False)

    op.create_table('test_observations',
    sa.Column('test_instance_id', sa.Uuid(), nullable=False),
    sa.Column('observation_no', sa.Integer(), nullable=False),
    sa.Column('position_label', sa.String(length=60), nullable=True),
    sa.Column('load', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('indication', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('additional_load', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('elapsed_seconds', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('input_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('anomaly_flag', sa.String(length=24), nullable=True),
    sa.Column('anomaly_note', sa.Text(), nullable=True),
    sa.Column('anomaly_disposition', sa.String(length=24), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_instance_id'], ['test_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_observations_test_instance_id'), ['test_instance_id'], unique=False)

    op.create_table('compliance_results',
    sa.Column('test_instance_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('measured_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('limit_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('margin', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('rule_id', sa.String(length=80), nullable=True),
    sa.Column('rule_version', sa.String(length=80), nullable=True),
    sa.Column('clause_reference', sa.String(length=80), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_instance_id'], ['test_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_results_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_results_test_instance_id'), ['test_instance_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_results_test_instance_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_results_status'))

    op.drop_table('compliance_results')
    with op.batch_alter_table('test_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_observations_test_instance_id'))

    op.drop_table('test_observations')
    with op.batch_alter_table('test_equipment_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_equipment_usage_test_instance_id'))
        batch_op.drop_index(batch_op.f('ix_test_equipment_usage_equipment_id'))
        batch_op.drop_index(batch_op.f('ix_test_equipment_usage_case_id'))

    op.drop_table('test_equipment_usage')
    with op.batch_alter_table('report_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_revisions_report_id'))

    op.drop_table('report_revisions')
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_overrides_test_instance_id'))

    op.drop_table('manual_overrides')
    with op.batch_alter_table('environmental_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environmental_conditions_test_instance_id'))
        batch_op.drop_index(batch_op.f('ix_environmental_conditions_case_id'))

    op.drop_table('environmental_conditions')
    with op.batch_alter_table('calculation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_runs_test_instance_id'))
        batch_op.drop_index(batch_op.f('ix_calculation_runs_test_code'))

    op.drop_table('calculation_runs')
    with op.batch_alter_table('attachment_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_links_test_instance_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_links_case_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_links_attachment_id'))

    op.drop_table('attachment_links')
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_actions_case_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_actions_actor_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_actions_action'))
        batch_op.drop_index(batch_op.f('ix_workflow_actions_acted_at'))

    op.drop_table('workflow_actions')
    with op.batch_alter_table('test_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_instances_test_definition_id'))
        batch_op.drop_index(batch_op.f('ix_test_instances_status'))
        batch_op.drop_index(batch_op.f('ix_test_instances_result_status'))
        batch_op.drop_index(batch_op.f('ix_test_instances_case_id'))

    op.drop_table('test_instances')
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_reports_verification_code'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_status'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_report_no'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_content_hash'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_case_id'))

    op.drop_table('generated_reports')
    with op.batch_alter_table('case_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_case_assignments_case_id'))

    op.drop_table('case_assignments')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_sha256'))
        batch_op.drop_index(batch_op.f('ix_attachments_case_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_standard_version_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_manufacturer_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_laboratory_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_engineer_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_approver_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_application_no'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_applicant_id'))

    op.drop_table('evaluation_cases')
    with op.batch_alter_table('report_template_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_template_versions_template_id'))

    op.drop_table('report_template_versions')
    with op.batch_alter_table('test_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_definitions_test_code'))
        batch_op.drop_index(batch_op.f('ix_test_definitions_standard_version_id'))

    op.drop_table('test_definitions')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_version_label'))
        batch_op.drop_index(batch_op.f('ix_rule_versions_standard_version_id'))
        batch_op.drop_index(batch_op.f('ix_rule_versions_rule_id'))

    op.drop_table('rule_versions')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_code'))

    op.drop_table('report_templates')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_case_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('instrument_ranges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrument_ranges_instrument_id'))

    op.drop_table('instrument_ranges')
    with op.batch_alter_table('equipment_calibrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_calibrations_valid_until'))
        batch_op.drop_index(batch_op.f('ix_equipment_calibrations_equipment_id'))

    op.drop_table('equipment_calibrations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_role_code'))
        batch_op.drop_index(batch_op.f('ix_users_laboratory_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('test_equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_equipment_laboratory_id'))
        batch_op.drop_index(batch_op.f('ix_test_equipment_code'))

    op.drop_table('test_equipment')
    with op.batch_alter_table('standard_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_versions_standard_id'))
        batch_op.drop_index(batch_op.f('ix_standard_versions_is_active'))

    op.drop_table('standard_versions')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_code'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_code'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_serial_number'))
        batch_op.drop_index(batch_op.f('ix_instruments_model'))
        batch_op.drop_index(batch_op.f('ix_instruments_manufacturer_id'))
        batch_op.drop_index(batch_op.f('ix_instruments_instrument_class'))

    op.drop_table('instruments')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('standards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standards_code'))

    op.drop_table('standards')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_code'))
        batch_op.drop_index(batch_op.f('ix_rules_category'))

    op.drop_table('rules')
    op.drop_table('roles')
    op.drop_table('permissions')
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manufacturers_name'))
        batch_op.drop_index(batch_op.f('ix_manufacturers_code'))

    op.drop_table('manufacturers')
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laboratories_code'))

    op.drop_table('laboratories')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_laboratory_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_case_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applicants_name'))
        batch_op.drop_index(batch_op.f('ix_applicants_code'))

    op.drop_table('applicants')
    with op.batch_alter_table('ai_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_events_test_instance_id'))
        batch_op.drop_index(batch_op.f('ix_ai_events_feature_code'))
        batch_op.drop_index(batch_op.f('ix_ai_events_case_id'))

    op.drop_table('ai_events')
    # ### end Alembic commands ###