"""add the optional report signature layer

Revision ID: 0002
Revises: 0001
Created: 2026-09-29 19:48:20.315377

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
# Rendered rather than imported by Alembic: JSONB's astext_type comes out as a
# bare `Text()`, which would be a NameError without this line.
from sqlalchemy import Text  # noqa: F401


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_signatures',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('algorithm', sa.String(length=60), nullable=True),
    sa.Column('signer_identity', sa.String(length=255), nullable=True),
    sa.Column('signer_user_id', sa.Uuid(), nullable=True),
    sa.Column('certificate_reference', sa.String(length=512), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['generated_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['report_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_signatures_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_signatures_revision_id'), ['revision_id'], unique=False)

    # A NOT NULL column cannot be added to a table that already has rows
    # without a server default, so it is added with one and the default is
    # then dropped: the final schema matches the model exactly, which is what
    # `alembic check` (and the drift test) asserts.
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('signature_status', sa.String(length=24), nullable=False,
                      server_default='NOT_SIGNED')
        )
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.alter_column('signature_status', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_column('signature_status')

    with op.batch_alter_table('report_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_signatures_revision_id'))
        batch_op.drop_index(batch_op.f('ix_report_signatures_report_id'))

    op.drop_table('report_signatures')
    # ### end Alembic commands ###