"""mark the seeded demonstration accounts

Revision ID: 0003
Revises: 0002
Created: 2026-09-29 19:54:28.845962

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
# Rendered rather than imported by Alembic: JSONB's astext_type comes out as a
# bare `Text()`, which would be a NameError without this line.
from sqlalchemy import Text  # noqa: F401


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


# The accounts every previous release seeded. They are the demonstration logins,
# so the backfill below marks the rows that already exist rather than leaving
# them false and requiring a re-seed to get the demo panel back.
DEMO_EMAILS = (
    'admin@metriq.local',
    'labadmin@metriq.local',
    'engineer@metriq.local',
    'reviewer@metriq.local',
    'approver@metriq.local',
    'auditor@metriq.local',
)


def upgrade() -> None:
    # A NOT NULL column cannot be added to a table that already has rows without
    # a server default; the default is dropped straight afterwards so the final
    # schema matches the model exactly (which `alembic check` asserts).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.false())
        )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_demo', server_default=None)
    op.execute(
        "update users set is_demo = true where email in ("
        + ", ".join(repr(email) for email in DEMO_EMAILS)
        + ")"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    # ### end Alembic commands ###