"""govern the ruleset lifecycle and record metrology reviews

Revision ID: 4e0ca7bb29b3
Revises: 0004
Created: 2026-09-29 20:24:58.486387

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
# Rendered rather than imported by Alembic: JSONB's astext_type comes out as a
# bare `Text()`, which would be a NameError without this line.
from sqlalchemy import Text  # noqa: F401


revision = '4e0ca7bb29b3'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_reviews',
    sa.Column('standard_version_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('reviewer_name', sa.String(length=160), nullable=False),
    sa.Column('reviewer_credentials', sa.String(length=255), nullable=True),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('source_revision', sa.String(length=255), nullable=True),
    sa.Column('clause_reference', sa.String(length=80), nullable=True),
    sa.Column('boundary_cases_passed', sa.Boolean(), nullable=True),
    sa.Column('boundary_case_reference', sa.String(length=255), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fingerprint', sa.String(length=72), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_reviews_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_reviews_rule_version_id'), ['rule_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_reviews_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_reviews_standard_version_id'), ['standard_version_id'], unique=False)

    with op.batch_alter_table('standard_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('submitted_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('review_reference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('approval_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_for', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deactivated_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('deactivation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approved_fingerprint', sa.String(length=72), nullable=True))
        batch_op.add_column(sa.Column('activation_basis', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard_versions', schema=None) as batch_op:
        batch_op.drop_column('activation_basis')
        batch_op.drop_column('approved_fingerprint')
        batch_op.drop_column('deactivation_reason')
        batch_op.drop_column('deactivated_by')
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('scheduled_at')
        batch_op.drop_column('scheduled_for')
        batch_op.drop_column('approval_note')
        batch_op.drop_column('approved_by_name')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('review_reference')
        batch_op.drop_column('submitted_by')
        batch_op.drop_column('submitted_at')

    with op.batch_alter_table('rule_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_reviews_standard_version_id'))
        batch_op.drop_index(batch_op.f('ix_rule_reviews_scope'))
        batch_op.drop_index(batch_op.f('ix_rule_reviews_rule_version_id'))
        batch_op.drop_index(batch_op.f('ix_rule_reviews_decision'))

    op.drop_table('rule_reviews')
    # ### end Alembic commands ###