"""Persistence of generated test plans (FR-07).

The plan is generated by the pure functions in :mod:`plan` and then written as
one ``test_instances`` row per catalogue entry, so the exact plan used for an
evaluation is preserved and auditable.
"""

from __future__ import annotations

from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import EvaluationCase, TestDefinition, TestInstance, User, utcnow
from app.services import audit_service
from app.services.test_engine.plan import build_applicability_context, generate_plan


def generate_and_persist_plan(
    db: Session, *, case: EvaluationCase, user: User | None = None
) -> list[TestInstance]:
    """(Re)generate the case test plan from the active ruleset."""
    definitions = db.execute(
        select(TestDefinition)
        .where(
            TestDefinition.standard_version_id == case.standard_version_id,
            TestDefinition.is_active.is_(True),
        )
        .order_by(TestDefinition.sequence_no)
    ).scalars().all()
    if not definitions:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                "No active test definitions exist for the selected standards version. "
                "Seed or activate a ruleset before creating evaluation cases."
            ),
        )

    context = build_applicability_context(case.instrument, case=case)
    plan = generate_plan(definitions, context=context)
    by_code = {definition.test_code: definition for definition in definitions}

    for existing in list(case.tests):
        db.delete(existing)
    db.flush()

    created: list[TestInstance] = []
    for item in plan:
        definition = by_code.get(item.test_code)
        if definition is None:  # defensive: plan items always originate from definitions
            continue
        instance = TestInstance(
            case_id=case.id,
            test_definition_id=definition.id,
            sequence_no=item.sequence_no,
            applicability_status="APPLICABLE" if item.applicable else "NOT_APPLICABLE",
            applicability_reason=item.reason,
            applicability_trace={"checks": item.trace, "evaluated_at": utcnow().isoformat()},
        )
        db.add(instance)
        created.append(instance)

    case.test_plan_snapshot = {
        "generated_at": utcnow().isoformat(),
        "ruleset_label": case.standard_version.version_label if case.standard_version else None,
        "items": [item.as_dict() for item in plan],
    }
    case.test_plan_generated_at = utcnow()
    db.flush()

    audit_service.record(
        db,
        event_type="CREATE",
        entity_type="test_plan",
        entity_id=case.id,
        actor=user,
        case_id=case.id,
        after={
            "applicable": sum(1 for item in plan if item.applicable),
            "not_applicable": sum(1 for item in plan if not item.applicable),
            "ruleset_label": case.test_plan_snapshot["ruleset_label"],
        },
    )
    return created
